name: Export PlantUML diagrams

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  render-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
          since_last_remote_commit: true 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Get changed UML files
        id: get-changed-uml-files
        run: |
          puml_files=''
          for changed_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            extension="${changed_file##*.}"

            if [ "${extension}" == "puml" ]; then
              puml_files="${puml_files} ${changed_file}"
              echo "Added file: ${changed_file}"
            fi
          done
          echo "puml-files=${puml_files}" >> $GITHUB_OUTPUT
          
      - name: Generate SVG Diagrams
        uses: dreamsinbits/export-plantuml-action@v1
        with:
          args: -v -o out -tsvg ${{ steps.get-changed-uml-files.outputs.puml-files }}
          
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_user_name: "PlantUML Diagramm Renderer"
          commit_user_email: "plantuml@your-domain.com"
          commit_author: "PLantUML <plantuml@your-domain.com>"
          commit_message: "Generated SVG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
